# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.23)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS Panda3D::Tools::pencrypt Panda3D::Tools::pdecrypt Panda3D::Tools::pzip Panda3D::Tools::punzip Panda3D::Tools::multify Panda3D::Tools::pview Panda3D::Tools::bam-info Panda3D::Tools::egg2bam Panda3D::Tools::bam2egg Panda3D::Tools::pts2bam Panda3D::Tools::dxf-points Panda3D::Tools::egg2dxf Panda3D::Tools::dxf2egg Panda3D::Tools::egg-crop Panda3D::Tools::egg-list-textures Panda3D::Tools::egg-make-tube Panda3D::Tools::egg-rename Panda3D::Tools::egg-retarget-anim Panda3D::Tools::egg-texture-cards Panda3D::Tools::egg2c Panda3D::Tools::egg-topstrip Panda3D::Tools::egg-trans Panda3D::Tools::egg-mkfont Panda3D::Tools::egg-optchar Panda3D::Tools::egg-palettize Panda3D::Tools::p3txafile Panda3D::Tools::egg-qtess Panda3D::Tools::flt-info Panda3D::Tools::flt-trans Panda3D::Tools::egg2flt Panda3D::Tools::flt2egg Panda3D::Tools::gtk-stats Panda3D::Tools::image-fix-hidden-color Panda3D::Tools::image-info Panda3D::Tools::image-resize Panda3D::Tools::image-transform-colors Panda3D::Tools::image-trans Panda3D::Tools::lwo-scan Panda3D::Tools::lwo2egg Panda3D::Tools::bin2c Panda3D::Tools::egg2obj Panda3D::Tools::obj2egg Panda3D::Tools::pfm-bba Panda3D::Tools::pfm-trans Panda3D::Tools::p3ptloader Panda3D::Tools::text-stats Panda3D::Tools::vrml-trans Panda3D::Tools::vrml2egg Panda3D::Tools::x-trans Panda3D::Tools::egg2x Panda3D::Tools::x2egg)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target Panda3D::Tools::pencrypt
add_executable(Panda3D::Tools::pencrypt IMPORTED)

# Create imported target Panda3D::Tools::pdecrypt
add_executable(Panda3D::Tools::pdecrypt IMPORTED)

# Create imported target Panda3D::Tools::pzip
add_executable(Panda3D::Tools::pzip IMPORTED)

# Create imported target Panda3D::Tools::punzip
add_executable(Panda3D::Tools::punzip IMPORTED)

# Create imported target Panda3D::Tools::multify
add_executable(Panda3D::Tools::multify IMPORTED)

# Create imported target Panda3D::Tools::pview
add_executable(Panda3D::Tools::pview IMPORTED)

# Create imported target Panda3D::Tools::bam-info
add_executable(Panda3D::Tools::bam-info IMPORTED)

# Create imported target Panda3D::Tools::egg2bam
add_executable(Panda3D::Tools::egg2bam IMPORTED)

# Create imported target Panda3D::Tools::bam2egg
add_executable(Panda3D::Tools::bam2egg IMPORTED)

# Create imported target Panda3D::Tools::pts2bam
add_executable(Panda3D::Tools::pts2bam IMPORTED)

# Create imported target Panda3D::Tools::dxf-points
add_executable(Panda3D::Tools::dxf-points IMPORTED)

# Create imported target Panda3D::Tools::egg2dxf
add_executable(Panda3D::Tools::egg2dxf IMPORTED)

# Create imported target Panda3D::Tools::dxf2egg
add_executable(Panda3D::Tools::dxf2egg IMPORTED)

# Create imported target Panda3D::Tools::egg-crop
add_executable(Panda3D::Tools::egg-crop IMPORTED)

# Create imported target Panda3D::Tools::egg-list-textures
add_executable(Panda3D::Tools::egg-list-textures IMPORTED)

# Create imported target Panda3D::Tools::egg-make-tube
add_executable(Panda3D::Tools::egg-make-tube IMPORTED)

# Create imported target Panda3D::Tools::egg-rename
add_executable(Panda3D::Tools::egg-rename IMPORTED)

# Create imported target Panda3D::Tools::egg-retarget-anim
add_executable(Panda3D::Tools::egg-retarget-anim IMPORTED)

# Create imported target Panda3D::Tools::egg-texture-cards
add_executable(Panda3D::Tools::egg-texture-cards IMPORTED)

# Create imported target Panda3D::Tools::egg2c
add_executable(Panda3D::Tools::egg2c IMPORTED)

# Create imported target Panda3D::Tools::egg-topstrip
add_executable(Panda3D::Tools::egg-topstrip IMPORTED)

# Create imported target Panda3D::Tools::egg-trans
add_executable(Panda3D::Tools::egg-trans IMPORTED)

# Create imported target Panda3D::Tools::egg-mkfont
add_executable(Panda3D::Tools::egg-mkfont IMPORTED)

# Create imported target Panda3D::Tools::egg-optchar
add_executable(Panda3D::Tools::egg-optchar IMPORTED)

# Create imported target Panda3D::Tools::egg-palettize
add_executable(Panda3D::Tools::egg-palettize IMPORTED)

# Create imported target Panda3D::Tools::p3txafile
add_library(Panda3D::Tools::p3txafile SHARED IMPORTED)

# Create imported target Panda3D::Tools::egg-qtess
add_executable(Panda3D::Tools::egg-qtess IMPORTED)

# Create imported target Panda3D::Tools::flt-info
add_executable(Panda3D::Tools::flt-info IMPORTED)

# Create imported target Panda3D::Tools::flt-trans
add_executable(Panda3D::Tools::flt-trans IMPORTED)

# Create imported target Panda3D::Tools::egg2flt
add_executable(Panda3D::Tools::egg2flt IMPORTED)

# Create imported target Panda3D::Tools::flt2egg
add_executable(Panda3D::Tools::flt2egg IMPORTED)

# Create imported target Panda3D::Tools::gtk-stats
add_executable(Panda3D::Tools::gtk-stats IMPORTED)

# Create imported target Panda3D::Tools::image-fix-hidden-color
add_executable(Panda3D::Tools::image-fix-hidden-color IMPORTED)

# Create imported target Panda3D::Tools::image-info
add_executable(Panda3D::Tools::image-info IMPORTED)

# Create imported target Panda3D::Tools::image-resize
add_executable(Panda3D::Tools::image-resize IMPORTED)

# Create imported target Panda3D::Tools::image-transform-colors
add_executable(Panda3D::Tools::image-transform-colors IMPORTED)

# Create imported target Panda3D::Tools::image-trans
add_executable(Panda3D::Tools::image-trans IMPORTED)

# Create imported target Panda3D::Tools::lwo-scan
add_executable(Panda3D::Tools::lwo-scan IMPORTED)

# Create imported target Panda3D::Tools::lwo2egg
add_executable(Panda3D::Tools::lwo2egg IMPORTED)

# Create imported target Panda3D::Tools::bin2c
add_executable(Panda3D::Tools::bin2c IMPORTED)

# Create imported target Panda3D::Tools::egg2obj
add_executable(Panda3D::Tools::egg2obj IMPORTED)

# Create imported target Panda3D::Tools::obj2egg
add_executable(Panda3D::Tools::obj2egg IMPORTED)

# Create imported target Panda3D::Tools::pfm-bba
add_executable(Panda3D::Tools::pfm-bba IMPORTED)

# Create imported target Panda3D::Tools::pfm-trans
add_executable(Panda3D::Tools::pfm-trans IMPORTED)

# Create imported target Panda3D::Tools::p3ptloader
add_library(Panda3D::Tools::p3ptloader MODULE IMPORTED)

# Create imported target Panda3D::Tools::text-stats
add_executable(Panda3D::Tools::text-stats IMPORTED)

# Create imported target Panda3D::Tools::vrml-trans
add_executable(Panda3D::Tools::vrml-trans IMPORTED)

# Create imported target Panda3D::Tools::vrml2egg
add_executable(Panda3D::Tools::vrml2egg IMPORTED)

# Create imported target Panda3D::Tools::x-trans
add_executable(Panda3D::Tools::x-trans IMPORTED)

# Create imported target Panda3D::Tools::egg2x
add_executable(Panda3D::Tools::egg2x IMPORTED)

# Create imported target Panda3D::Tools::x2egg
add_executable(Panda3D::Tools::x2egg IMPORTED)

# Load information for each installed configuration.
file(GLOB _cmake_config_files "${CMAKE_CURRENT_LIST_DIR}/Panda3DToolsTargets-*.cmake")
foreach(_cmake_config_file IN LISTS _cmake_config_files)
  include("${_cmake_config_file}")
endforeach()
unset(_cmake_config_file)
unset(_cmake_config_files)

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(_cmake_target IN LISTS _cmake_import_check_targets)
  foreach(_cmake_file IN LISTS "_cmake_import_check_files_for_${_cmake_target}")
    if(NOT EXISTS "${_cmake_file}")
      message(FATAL_ERROR "The imported target \"${_cmake_target}\" references the file
   \"${_cmake_file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_cmake_file)
  unset("_cmake_import_check_files_for_${_cmake_target}")
endforeach()
unset(_cmake_target)
unset(_cmake_import_check_targets)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
